# Generated by Django 5.2.4 on 2025-07-08 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_style', models.CharField(choices=[('ADVENTURE', 'Adventure'), ('RELAXATION', 'Relaxation'), ('CULTURAL', 'Cultural'), ('FAMILY', 'Family'), ('BUDGET', 'Budget')], default='RELAXATION', max_length=20)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text="User's approximate budget per day in USD.", max_digits=10, null=True)),
                ('preferred_languages', models.CharField(default='English', help_text='Comma-separated list of preferred languages.', max_length=100)),
                ('avatar', models.ImageField(blank=True, help_text="User's profile picture.", null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
