# In planner/urls.py
from django.urls import path, include
from rest_framework_nested import routers 
from .views import AIRecommendationView, ItineraryViewSet, ItineraryItemViewSet 
from .views import WeatherAlertsView
from .views import CulturalEventsView
from .views import ItineraryRouteView

# The top-level router for itineraries
router = routers.SimpleRouter()
router.register(r'itineraries', ItineraryViewSet, basename='itinerary')

# The nested router for items within an itinerary
# It gets the 'itinerary_pk' from the parent router
items_router = routers.NestedSimpleRouter(router, r'itineraries', lookup='itinerary')
items_router.register(r'items', ItineraryItemViewSet, basename='itinerary-items')

urlpatterns = [
    # Manually added view
    path('recommendations/', AIRecommendationView.as_view(), name='ai_recommendations'),

    # New manual URL for weather alerts
    path('itineraries/<int:itinerary_pk>/alerts/', WeatherAlertsView.as_view(), name='itinerary-alerts'),
    path('events/', CulturalEventsView.as_view(), name='cultural-events'),
    
    # URLs generated by the routers
    path('', include(router.urls)),
    path('', include(items_router.urls)),
]

urlpatterns += [
    path('itineraries/<int:itinerary_pk>/optimize-route/', ItineraryRouteView.as_view(), name='itinerary-route'),
]