# Generated by Django 5.2.4 on 2025-07-08 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('destination_type', models.CharField(choices=[('LANDMARK', 'Landmark'), ('MUSEUM', 'Museum'), ('RESTAURANT', 'Restaurant'), ('PARK', 'Park'), ('HIKING_TRAIL', 'Hiking Trail'), ('BEACH', 'Beach')], max_length=20)),
                ('average_cost', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinations', models.ManyToManyField(blank=True, related_name='itineraries', to='planner.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
