# Generated by Django 5.2.4 on 2025-07-08 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_seed_destinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='destinations',
        ),
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='Day number in the trip, e.g., 1, 2, 3.')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='planner.destination')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planner.itinerary')),
            ],
            options={
                'ordering': ['day_number', 'start_time'],
            },
        ),
    ]
