# Generated by Django 5.2.4 on 2025-07-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_remove_itinerary_destinations_destination_latitude_and_more'),
        ('planner', '0004_update_destination_coords'),
    ]

    operations = [
    ]
